### ISSUE TITLE
ExtractArea.java doesn't compile

### ISSUE THREAD

**Issue by ctmartin12** [openskynetwork/osky-sample#2]
pos.distanceTo needs to be changed to pos.haversine  for ExtractArea.java to compile since the method name was changed in java-adsb

**Comment by yhhabiboglu** [comment]
thanks

**Comment by slevon** [comment]
Hello, I just tried to compile the java tools, and the problem seems to persist. However, the pull request from @yhhabiboglu fixes the issue. 
Do you plan to merge the pull request?

**Comment by affitz** [comment]
Merged, thanks!
